feat: fix elevenlabs >=2.3.0 api change (#102)
In "elevenlabs>=2.3.0", the below errors occur because elevenlabs in
langchain_community.tools is not compatible new version api.

when use tts.run, the error is:
RuntimeError: Error while running ElevenLabsText2SpeechTool: a
bytes-like object is required, not 'generator'

when use tts.stream_speech, the error is:
AttributeError: 'RealtimeTextToSpeechClient' object has no attribute
'convert_as_stream'

Co-authored-by: Mason Daugherty <mason@langchain.dev>